### ISSUE TITLE
Types in file `shared/src/options/model.ts` is not published in the node package for use with Programmatic API

### ISSUE THREAD

**Issue by sharky98** [nativefier/nativefier#1466]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

Programmatic API - See files scripts in debug info.

### Steps to reproduce

I wanted to build some apps with the programmatic API with Typescript. I am using pnpm in isolated mode for installation of deps.

1. Create Project (`pnpm init`) and add scripts in `package.json`
2. Configure Typescript in `tsconfig.json`
3. Write a typed Typescript code to build an app using the `buildNativefierApp` function.
4. Try to put the options in an `const` object instead of the function arguments <<== Fail here!

Sidenote, in the [API.md](https://github.com/nativefier/nativefier/blob/master/API.md#programmatic-api), the `nativefier` function is shown as deprecated since 7.7.2 when using it and ask to use `buildNativefierApp` instead.

### Expected behavior

Types from the file `shared/src/options/model.ts` are exported and available in the npm package by Nativefier (in `lib/main.d.ts`)

### Actual behavior

Types from the file `shared/src/options/model.ts` are import from a non existing file in the npm package by Nativefier (in `lib/main.d.ts`). They are not re-exported either.

`main.d.ts` showing RawOptions imported.
![image](https://user-images.githubusercontent.com/8150191/193592549-176e81d2-3bad-433b-893a-0af50c95e62c.png)

Node_modules package, no `shared` folder under lib.
![image](https://user-images.githubusercontent.com/8150191/193592666-a498e27a-be5b-4af6-8d0d-3e362e3accea.png)

### Debug info

# Directory structure

```shell
my-nativefier-configs/
├── package.json
├── tsconfig.json
└── build-config/
    └── ms365/
        └── to-do.ts
```

## package.json
```json
{
  "name": "nativefier",
  "description": "config for my webapp nativefied",
  "dependencies": {
    "nativefier": "^50.0.0"
  },
  "scripts": {
    "build": "pnpm tsc",
    "build:todo": "pnpm exec node ./dist/ms365/to-do.js"
  },
  "devDependencies": {
    "@types/node": "^18.7.23",
    "typescript": "^4.8.4"
  }
}
```

## tsconfig.json
```json
{
  "compilerOptions": {
    /* Language and Environment */
    // Configured for Node >= 16 (https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping#node-16)
    "target": "ES2021",
    "lib": ["ES2021"],

    /* Modules */
    "module": "CommonJS",
    "rootDir": "./build-config",

    /* Emit */
    "outDir": "./dist",
    "importHelpers": false,
    "sourceMap": true,

    /* Interop Constraints */
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    /* Type Checking */
    "strict": true,

    /* Completeness */
    "skipLibCheck": true
  }
}

```

## to-do.ts
```typescript
#!/usr/bin/env node

import { buildNativefierApp } from "nativefier";
import type { RawOptions } from "../nativerfier.options";
import path from "path";
import { existsSync, mkdirSync } from "fs";

const buildDir = path.resolve(process.cwd(), "builds", "ms365");

if (!existsSync(buildDir)) {
  mkdirSync(buildDir, { recursive: true });
}

// possible options, defaults unless specified otherwise
const options: RawOptions = {
  targetUrl: "https://to-do.live.com/tasks/", // required
  out: buildDir,
};

console.log("🚀 Starting the build of MS365 To Do app.\n");

buildNativefierApp(options)
  .then((result) => {
    console.log("\n🏁 Completed with success ✅");
    console.log(result);
  })
  .catch((err) => {
    console.log("\n❗️ Failed ❌");
    console.error(err);
  });

```

### Nativefier version

5.0.0

### Node.js version

v18.9.1

### npm version

pnpm 7.12.2

### OS

Ubuntu 22.04 (Jammy)
